# Generated by Django 2.2.6 on 2019-10-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_hash', models.CharField(max_length=255)),
                ('date_found', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('job_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topskills.Job')),
            ],
        ),
    ]
