# Generated by Django 2.2.6 on 2019-10-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topskills', '0002_auto_20191021_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
