# Generated by Django 2.2.6 on 2019-10-22 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topskills', '0003_auto_20191021_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_viable_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 12, 49, 35, 986875)),
        ),
    ]
