# Generated by Django 2.2.6 on 2019-10-22 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topskills', '0004_job_date_viable_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_viable_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 12, 50, 24, 87301)),
        ),
    ]
