# Generated by Django 2.2.6 on 2019-10-23 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topskills', '0005_auto_20191022_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_url',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_viable_to',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 14, 14, 0, 899715)),
        ),
    ]
